version: '3.9'

services:
  admin_panel:
    container_name: admin_panel
    build: ./admin_panel/
    expose:
      - "8000"
    depends_on:
      - cinema_db
    env_file:
      - ./.env
    networks:
      - app_network
    volumes:
      - static:/opt/app/static
      - media:/opt/app/media
      - ./admin_panel:/opt/app

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/data/static
      - media:/data/media
    depends_on:
      - admin_panel
      - api
    ports:
      - "80:80"
    networks:
      - app_network

  cinema_db:
    image: postgres:latest
    container_name: cinema_db
    env_file:
      - ./.env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./admin_panel/database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  elastic:
    image: elasticsearch:9.1.5
    container_name: elastic
    restart: always
    expose:
      - "9200"
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "ES_HEAP_SIZE=512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  init-elastic:
    image: curlimages/curl:latest
    container_name: elastic_init
    depends_on:
      elastic:
        condition: service_healthy
    volumes:
      - ./etl_service/init-elastic.sh:/scripts/init-elastic.sh
    command: > 
      sh -c "chmod +x /scripts/*.sh && /scripts/init-elastic.sh"
    env_file:
      - ./.env
    networks:
      - app_network

  etl:
    build: ./etl_service
    container_name: etl
    restart: always
    depends_on:
      cinema_db:
        condition: service_healthy
      elastic:
        condition: service_healthy
      init-elastic:
        condition: service_completed_successfully
    env_file:
      - ./.env
    networks:
      - app_network
  redis:
    image: redis:8.2-alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/redis_data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network
  api:
    build: ./async_api
    container_name: api
    restart: always
    volumes:
      - ./async_api:/app/
    depends_on:
      elastic:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - app_network
  auth_service:
    build: ./auth_service
    container_name: auth_service
    restart: always
    volumes:
      - ./auth_service:/app/
    depends_on:
      - cinema_db
      - redis
    env_file:
      - ./.env
    networks:
      - app_network

  ugc:
    build: ./ugc_service
    container_name: ugc
    env_file:
      - ./.env
    volumes:
      - ./ugc_service:/opt/app
    networks:
      - app_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: content
    volumes:
      - mongo_db:/data/db
    networks:
      - app_network

  kibana:
    image: kibana:9.1.5
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - app_network
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

  logstash:
    image: logstash:8.10.2
    container_name: logstash
    depends_on:
      - elastic
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elastic:9200"
    ports:
      - "5044:5044"
      - "5045:5045"
    networks:
      - app_network
    volumes:
      - ./ugc_service/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    restart: always
    expose:
      - "9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=0
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 10

    volumes:
      - kafka_0_data:/bitnami/kafka

  ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: kafka_ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - app_network
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft
  notification:
    build: ./notification_service/src
    container_name: notification
    env_file:
      - ./.env
    volumes:
      - ./notification_service/src:/opt/app
    depends_on:
      - mongodb
    networks:
      - app_network
  worker:
    build: ./notification_service/worker
    container_name: worker
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./notification_service/worker:/opt/app
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app_network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static:
  media:
  postgres_data:
  elasticsearch_data:
  redis_data:
  mongo_db:
  kibana_data:
  kafka_0_data: