# Generated by Django 5.0.4 on 2026-03-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_together', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filmwork',
            table='film_work',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
        migrations.AlterModelTable(
            name='genrefilmwork',
            table='genre_film_work',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='personfilmwork',
            table='person_film_work',
        ),
    ]
